services:

  login001:
    build: .
    hostname: login001
    mem_limit: 24G
    mem_reservation: 24G
    networks:
      compute:
      inband:
        aliases:
          - login001.inband
      ib:
        aliases:
          - login001.ib
    ports:
      - "6322:22"
    volumes:
      - home:/home
      - etc_slurm:/etc/slurm
      - etc_munge:/etc/munge



  node0001:
    build: .
    hostname: node0001
    networks:
      compute:
      inband:
        aliases:
          - node0001.inband
      ib:
        aliases:
          - node0001.ib
    expose:
      - 22
    volumes:
      - home:/home
      - etc_slurm:/etc/slurm
      - etc_munge:/etc/munge

  node0002:
    build: .
    hostname: node0002
    networks:
      compute:
      inband:
        aliases:
          - node0002.inband
      ib:
        aliases:
          - node0002.ib
    expose:
      - 22
    volumes:
      - home:/home
      - etc_slurm:/etc/slurm
      - etc_munge:/etc/munge

  node0003:
    build: .
    hostname: node0003
    networks:
      compute:
      inband:
        aliases:
          - node0003.inband
      ib:
        aliases:
          - node0003.ib
    expose:
      - 22
    volumes:
      - home:/home
      - etc_slurm:/etc/slurm
      - etc_munge:/etc/munge

  node0004:
    build: .
    hostname: node0004
    networks:
      compute:
      inband:
        aliases:
          - node0004.inband
      ib:
        aliases:
          - node0004.ib
    expose:
      - 22
    volumes:
      - home:/home
      - etc_slurm:/etc/slurm
      - etc_munge:/etc/munge


volumes:
  etc_munge:
  etc_slurm:
  home:

  node0001_slurmd_state:

  node0002_slurmd_state:

  node0003_slurmd_state:

  node0004_slurmd_state:

  slurmctld_state:
  slurmdbd_state:

networks:
  compute:
  inband:
  ib: 